env:
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  project: ./tsconfig.json
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-unused-vars": ["warn", { "argsIgnorePattern": "^_" }]
ignorePatterns:
  - "/public/*"
