plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

# Check this fom time to time, the authors of the packages might fix it.
# Also, you should update the hardcoded dependencies if you cannot remove them.
packageExtensions:
  mocha@*:
    dependencies:
      ts-node: "^9.1.1"
    peerDependencies:
      typescript: "^4.2.4"
  react-dev-utils@*:
    peerDependencies:
      typescript: "^4.2.4"
      webpack: "^4.0.0"
