version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    networks:
      - voting-webapp
    volumes:
      - logs-volume:/src/logs
    ports:
      - 3003:3003
    depends_on:
      - mongo
    environment:
      - FORCE_COLOR=1
      - PORT=3003
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DBNAME=votacions
      - MONGO_USER=bestbarcelona
      - MONGO_PASSWORD=password
      - MONGO_TIMEOUT=5000
      - CERT_PATH=../../
      - COOKIE_KEY1=key1
      - COOKIE_KEY2=key2
      - ROOT_DIR=./
      - NODE_ENV=prod
      - CLIENT_ID=260328757466-cmmgec2o5sfm626bl33o5h1dekrmvfir.apps.googleusercontent.com
  mongo:
    image: mongo
    networks:
      - voting-webapp
    volumes:
      - mongo-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bestbarcelona
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=votacions
volumes:
  mongo-volume:
  logs-volume:
networks:
  voting-webapp:
